### ISSUE TITLE
Highlights sometimes include surrounding spaces

### ISSUE THREAD

**Issue by trickypr** [Dherse/codly#35] opened 2024-11-10 09:44 UTC
I have been helping someone debug some odd behavior with highlights in Haskell code. Specifically, this example (dashes are placeholders for backticks):
```
#import "./codly.typ": *

#show: codly-init.with()
#codly(
  highlights: (
    (line: 0, start: 15, fill: green),
    (line: 2, start: 3, fill: green),
  ),
)
---haskell
data Stream a m
  = Step a (Stream a)
  | Effect (m (Stream a m))
  | Done
---
```
Which, with the code in `main`, provides this output:
![image](https://github.com/user-attachments/assets/1147a197-49be-4244-b6df-ed96250effcc)

Note that the highlight includes the space before ` a m`. This is not the behavior we believe is intended. Instead, we would expect an output closer to this:
![image](https://github.com/user-attachments/assets/76629296-0346-430b-978f-8246e3d5704d)

One solution would be to remove any leading spaces from highlights, which I have done on a fork: https://github.com/trickypr/codly/commit/62ca7533c8f888a54f1b57650564f610b58d8a18.

**Comment by endgame** [comment] 2024-11-10 09:46
Thanks for posting this. I think even that's not going to be enough — my hope was to highlight only the type variable `m` in line 1. I don't understand typst's data model but I think it might be necessary to break unstyled blocks into runs of non-space characters?

**Comment by endgame** [comment] 2024-11-10 10:25
Hm, another thing I'd like to be able to do (on a future slide I was planning on writing): in the text `= Step !a (Stream a m)`, highlight only the `!`, or at least the `!a`. The smallest highiight I can get is `!a (`.

**Comment by Dherse** [comment] 2024-11-10 15:39
Yes I am aware of the issue, unfortunately I have tried many workarounds and none of them are generic. What happens is that sometimes Typst groups up several "tokens" into one `styled(...)` which is unfortunately opaque. If I could, I would simply take the style and re-apply it to all of its children but it's not possible which means I cannot *currently* fix this issue.

**Comment by endgame** [comment] 2024-11-10 21:35
When processing a code block, it sounds like Typst core needs to not merge text that has come from distinct tokens in the quoted language? It probably only shows up when it makes one big `styled(...)` for downstream libraries to use.

**Comment by Dherse** [comment] 2024-11-11 10:47
Exactly but I don't think this is necessarily typst's fault, internally typst call a crate (forgot which one) which does the syntax highlighting and having re-written that part of typst, I am confident in saying that typst doesn't group tokens any more than what the highlighting crates tells it too iirc.

**Comment by Aaron-Rumpler** [comment] 2024-11-11 10:57
> internally typst call a crate (forgot which one)

That would be [syntect](https://github.com/trishume/syntect). It also powers `bat`'s syntax highlighting. Looking at its output, it also groups the characters in exactly the same way as Typst does:
![Codly Test](https://github.com/user-attachments/assets/1bfdd859-f973-4956-a21a-ab339bd51a85)
![Bat Output](https://github.com/user-attachments/assets/24984c4b-2639-4806-88d9-63de0d13f968)

**Comment by Dherse** [comment] 2024-11-11 16:08
Indeed, you're correct the problem is that when it groups whitespaces, since they're contained in `styled` elements, it's tricky for me to fix it. @frozolotl told me he has a solution for this, waiting to hear back from him. Ideally, if Typst exposed an opaque `style` type, which AFAIK it at least used to, and a function to apply arbitrary styles then it could be done rather easily.

**Comment by Dherse** [comment] 2024-11-11 17:12
![image](https://github.com/user-attachments/assets/f3095f76-bfd2-4a73-bffe-92da3f13d5af)
It does indeed work, especially with a new flattening function for contents (probably very slow & memory hungry)

**Comment by Dherse** [comment] 2024-11-11 17:34
Fixed in [53bdb80](https://github.com/Dherse/codly/commit/53bdb808cf1c5a58e0b3d59901befbde93be4e20)

**Closed by Dherse** 2024-11-11 17:34 UTC

**Comment by Aaron-Rumpler** [comment] 2024-11-12 02:19
This will need updating as well:
https://github.com/Dherse/codly/blob/6b089b7d2535ec44f666e5f36d59770f51afb5dc/codly.typ#L812-L816

**Comment by Dherse** [comment] 2024-11-12 10:39
I am updating the docs so this will be gone :)
